### ISSUE TITLE
when sign in using admin:admin or register i get sqtracker API error: MongooseError: Operation users.findOne() buffering timed out after 10000ms

### ISSUE THREAD

**Issue by Mohanadawad12** [tdjsnelling/sqtracker#83]
![image](https://github.com/tdjsnelling/sqtracker/assets/88785140/1eddf68e-6a7d-4717-9de7-4c9c55ce1def)
login-dc7549a46473c8df.js:1 Error: sqtracker API error: MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at login-dc7549a46473c8df.js:1:1793
    at s (main-da87f8cfa59fe76a.js:1:93957)
    at Generator._invoke (main-da87f8cfa59fe76a.js:1:93745)
    at forEach.e.<computed> [as next] (main-da87f8cfa59fe76a.js:1:94380)
    at r (_app-daa81128f910edd9.js:1:396987)
    at s (_app-daa81128f910edd9.js:1:397190)
(anonymous) @ login-dc7549a46473c8df.js:1
s @ main-da87f8cfa59fe76a.js:1
(anonymous) @ main-da87f8cfa59fe76a.js:1
forEach.e.<computed> @ main-da87f8cfa59fe76a.js:1
r @ _app-daa81128f910edd9.js:1
s @ _app-daa81128f910edd9.js:1
Promise.then (async)
r @ _app-daa81128f910edd9.js:1
s @ _app-daa81128f910edd9.js:1Understand this error

**Comment by kkarthy** [comment]
Its to do with docker I got the same error i fixed it by changing 
`SQ_MONGO_URL: "mongodb://sq_mongodb/sqtracker",`
that line in the config.js file also this is how i figured it out 

```
karthy@Hydrogen ~/sqtracker
$ docker network inspect sqtracker_default
[
    {
        "Name": "sqtracker_default",
        "Id": "d8c431b67bdf9db75fa685222ff57e4778df9ce13dccad8d29bab8c6b5954e89",
        "Created": "2024-11-28T00:47:56.889655778Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "45e15adb8f56069d2b245e5a71bda9e52558cc22d42ef4ac863fd7789327eb54": {
                "Name": "sq_mongodb",
                "EndpointID": "b5fa87c885724dee02a907547c5f205f1bf4750004c593f9205c9bfbf1dedd92",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "556ce4edd5434fe3d334f6dafbd54c4587da5a4a1082f76643a1cdea4ea39610": {
                "Name": "sq_client",
                "EndpointID": "127f843bd7b0f3b6322138058e1ce779aa8308544f0eb3fe8c42a2751d597819",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "67afafec9c7d061fa55641ef1234087b9aaf5978f986efb1e04d5a78ff8a1760": {
                "Name": "sq_nginx",
                "EndpointID": "efaa8caec71d3fb1a1b86c5ec328609da4015e7c3490391f635717989e60a52e",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "ce0867dcd288b8d77fd38c4e15aa1c7999417c3627c7cc9667042c553b2abf6c": {
                "Name": "sq_api",
                "EndpointID": "60565ebc73adb557bde741a4dc1cc80dea12500f0fb91920966db9aceb2605ea",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "sqtracker",
            "com.docker.compose.version": "2.29.7"
        }
    }
]
```

The IPv4 address keeps changing so sq_api trys to connect to the wrong endpoint so you just connect to its name instead
